export const questionnaire = [
  {
    question_number: 1,
    question: "I am an action taker.",
    choices: null,
    answer: 0,
    scoring: "add 10 points for each 1 eg 1=10 - 2=20",
    max_score: 100,
  },
  {
    question_number: 2,
    question: "I am a procrastinator.",
    choices: null,
    answer: 0,
    scoring: "subract 10 points for each 1 eg 1=10 - 2=20",
    max_score: 0,
  },
  {
    question_number: 3,
    question: "I believe the cup is half-full.",
    choices: null,
    answer: 0,
    scoring: "add 10 points for each 1 eg 1=10 - 2=20",
    max_score: 100,
  },
  {
    question_number: 4,
    question: "I have a clear set of goals that I write down and review daily.",
    choices: null,
    answer: 0,
    scoring: "add 10 points for each 1 eg 1=10 - 2=20",
    max_score: 100,
  },
  {
    question_number: 5,
    question: "I am quick to ask for help.",
    choices: null,
    answer: 0,
    scoring: "add 10 points for each 1 eg 1=10 - 2=20",
    max_score: 100,
  },
  {
    question_number: 6,
    question: "I have a business coach or mentor who is available every day.",
    choices: null,
    answer: 0,
    scoring: "add 10 points for each 1 eg 1=10 - 2=20",
    max_score: 100,
  },
  {
    question_number: 7,
    question:
      "I prefer to hear sugarcoated feedback instead of the bitter truth.",
    choices: null,
    answer: 0,
    scoring: "subract 10 points for each 1 eg 1=10 - 2=20",
    max_score: 0,
  },
  {
    question_number: 8,
    question: "I am looking for ways to increase productivity.",
    choices: null,
    answer: 0,
    scoring: "add 10 points for each 1 eg 1=10 - 2=20",
    max_score: 100,
  },
  {
    question_number: 9,
    question: "I find it easy to delegate responsibilities.",
    choices: null,
    answer: 0,
    scoring: "add 10 points for each 1 eg 1=10 - 2=20",
    max_score: 100,
  },
  {
    question_number: 10,
    question: "I know my turnover and profitability at all times.",
    choices: null,
    answer: 0,
    scoring: "add 10 points for each 1 eg 1=10 - 2=20",
    max_score: 100,
  },
  {
    question_number: 11,
    question:
      "I have well-allocated budgets for each month, quarter, and year that are a stretch.",
    choices: null,
    answer: 0,
    scoring: "add 10 points for each 1 eg 1=10 - 2=20",
    max_score: 100,
  },
  {
    question_number: 12,
    question:
      "I have a clear mission, vision, values, and goals that are all written down.",
    choices: null,
    answer: 0,
    scoring: "add 10 points for each 1 eg 1=10 - 2=20",
    max_score: 100,
  },
  {
    question_number: 13,
    question:
      "What percentage of your business is locally stored (laptop, desktop, or server) compared to cloud-based storage?",
    choices: ["1-5%", "6-10%", "11-20%", "21% and above"],
    scoring: "add 25 points per level",
    max_score: 100,
  },
  {
    question_number: 14,
    question:
      "How many places do you store your data in? Eg. Google Drive, iCloud, OneDrive, Dropbox, Box, laptop drive, subscription server etc. Note: 5+ files (photos, documents, etc.) in one place counts as storage.",
    choices: ["1", "2", "3", "4+"],
    answer: null,
    scoring:
      "add 25 points for level A. subract 25 points for each b c d total possible subtraction is 75",
    max_score: 25,
  },
  {
    question_number: 15,
    question: "Do you have a paid CRM subscription?",
    choices: ["Yes", "No"],
    answer: null,
    scoring: "add 25 for yes subtract 25 for no",
    max_score: 25,
  },
  {
    question_number: 16,
    question:
      "What is the average percentage of your current database you add every month?",
    choices: ["1-5%", "6-10%", "11-20%", "21% and above"],
    answer: null,
    scoring: "add 10 points per level",
    max_score: 40,
  },
  {
    question_number: 17,
    question: "Do you use subscription project management software?",
    choices: ["Yes", "No"],
    answer: null,
    scoring: "add 25 for yes only",
    max_score: 25,
  },
  {
    question_number: 18,
    question:
      "Do you have a clearly documented digital system that includes all your policies, procedures, training videos, etc.  that is accessible to all staff anywhere and anytime?",
    choices: ["Yes", "No"],
    answer: null,
    scoring: "add 25 for yes only",
    max_score: 25,
  },
  {
    question_number: 19,
    question: "Do you have a clear marketing and social media plan?",
    choices: ["Yes", "No"],
    answer: null,
    scoring: "add 25 for yes and subtract 10 for no",
    max_score: 25,
  },
  {
    question_number: 20,
    question: "Do you have a clear sales process?",
    choices: ["Yes", "No"],
    answer: null,
    scoring: "add 25 for yes and subtract 25 for no",
    max_score: 25,
  },
  {
    question_number: 21,
    question: "How many applications do you use for your business?",
    choices: ["1-5", "6-10", "11-20", "21-30", "30+"],
    answer: null,
    scoring: "add 10 for a and b. subtract 10 for each other level",
    max_score: 20,
  },
  {
    question_number: 22,
    question:
      "Which of the following statements best describes your technological approach in business?",
    choices: [
      "I am reluctant to use technology.",
      "I am a tech junkie.",
      "I am neither of the above.",
    ],
    answer: null,
    scoring: "subtract 25 for a, subtract 10 for b and add 10 for c",
    max_score: 10,
  },
  {
    question_number: 23,
    question: "All tasks are done according to plan and on time.",
    choices: null,
    answer: 0,
    scoring: "add 10 points per level",
    max_score: 100,
  },
  {
    question_number: 24,
    question:
      "I am always in a state of stress due to financial pressure or workload.",
    choices: null,
    answer: 0,
    scoring: "subract 5 points per level",
    max_score: 0,
  },
  {
    question_number: 25,
    question:
      "All my team members know and understand the company mission, vision, values, and goals.",
    choices: null,
    answer: 0,
    scoring: "add 10 per level",
    max_score: 100,
  },
  {
    question_number: 26,
    question:
      "All my team members are clear on who our target market is and how to engage them.",
    choices: null,
    answer: 0,
    scoring: "add 10 per level",
    max_score: 100,
  },
  {
    question_number: 27,
    question: "There is a clear learning strategy for all staff to upskill.",
    choices: null,
    answer: 0,
    scoring: "add 10 per level",
    max_score: 100,
  },
  {
    question_number: 28,
    question:
      "All team members know their role and the roles of everyone in the team so they can collaborate effectively and support each other with their own genius. ",
    choices: null,
    answer: 0,
    scoring: "add 10 per level",
    max_score: 100,
  },
  {
    question_number: 29,
    question:
      "There is a clear mechanism in the business that enables all team members to offer ideas, build systems, and increase productivity.",
    choices: null,
    answer: 0,
    scoring: "add 10 per level",
    max_score: 100,
  },
  {
    question_number: 30,
    question: "I have a clear leadership growth plan.",
    choices: null,
    answer: 0,
    scoring: "add 10 per level",
    max_score: 100,
  },
  {
    question_number: 31,
    question:
      "As a business owner, what percentage of your daily tasks would you love to delegate if you had the resources and team to delegate to?",
    choices: null,
    answer: 0,
    scoring: "add 10 per level",
    max_score: 100,
  },
  {
    question_number: 32,
    question: "What percentage do you actually delegate to others?",
    choices: null,
    answer: 0,
    scoring: "add 10 per level",
    max_score: 100,
  },
];
